// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  Re-index the vault: walk tracks + videos, seed from `scope.md`, upsert
	 *  idempotently on `vault_path`. Never duplicates rows; never regresses
	 *  chunk progress.
	 */
	reindex: (vaultPath: string | null) => typedError<ReindexResponse, string>(__TAURI_INVOKE("reindex", { vaultPath })),
	/**
	 *  The daily queue: per track the next chunk in course order, stale items
	 *  flagged ahead of new ones, the Anki due total (or the offline note) in
	 *  the header. Requires the state store — without it the answer cannot be
	 *  honest, so the error says so (ADR 0003 degradation).
	 */
	getQueue: () => typedError<QueueDto, string>(__TAURI_INVOKE("get_queue")),
	/**
	 *  Grades a card: schedules via FSRS, persists card state + review row in
	 *  one transaction, returns the card as it now reads (the UI shows the next
	 *  due). Unknown grade spellings are rejected here, not in the domain.
	 */
	gradeCard: (cardId: number, grade: string, durationMs: number | null) => typedError<CardDto, string>(__TAURI_INVOKE("grade_card", { cardId, grade, durationMs })),
	/**
	 *  The review batch: kept cards due now, oldest first. The UI shows "nothing
	 *  due" for an empty batch — an empty cards table is a normal state, not an
	 *  error (requirements.md EARS).
	 */
	listDueCards: (limit: number | null) => typedError<CardDto[], string>(__TAURI_INVOKE("list_due_cards", { limit })),
	/**
	 *  Marks the chunk complete (`done`); the next chunk in that track's order
	 *  becomes "next" (requirements.md EARS).
	 */
	completeChunk: (chunkId: number) => typedError<null, string>(__TAURI_INVOKE("complete_chunk", { chunkId })),
	/**
	 *  The session still open, if any — so the UI can offer resume/stop after a
	 *  restart.
	 */
	getActiveSession: () => typedError<{
	session_id: number,
	/**  The chunk being studied (the open session's stage row names it). */
	chunk_id: number,
	/**  `false` while the session is open. */
	closed: boolean,
	/**  Logged seconds, present once the session is stopped. */
	duration_seconds: number | null,
} | null, string>(__TAURI_INVOKE("get_active_session")),
	/**
	 *  Opens a study session on the chunk: one session row + the study stage row
	 *  (migration 0001's `session_stages.stage` enum as-is — ADR 0005, Proposed,
	 *  may amend it). The chunk flips to `in_progress`; the queue surfaces it.
	 */
	startSession: (chunkId: number) => typedError<SessionDto, string>(__TAURI_INVOKE("start_session", { chunkId })),
	/**
	 *  Stops the open session: records end time + duration and closes the stage
	 *  row. The chunk stays `in_progress` — it resurfaces in the queue.
	 */
	stopSession: () => typedError<SessionDto, string>(__TAURI_INVOKE("stop_session")),
	getSettings: () => typedError<SettingsDto, string>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Partial update: `vault_path: null` leaves it unchanged (the screen only
	 *  sends what the user edits); a blank position clears that track's override.
	 *  Returns the stored state so the UI syncs to what actually persisted.
	 */
	setSettings: (settings: SettingsDto) => typedError<SettingsDto, string>(__TAURI_INVOKE("set_settings", { settings })),
};

/* Types */
/**
 *  Anki due header. Display-only — the total never gates the queue, and any
 *  Anki failure degrades to a note while the queue answers normally
 *  (specs/queue-slice/design.md point 3, requirements.md EARS).
 */
export type AnkiHeaderDto = {
	/**
	 *  Total due cards when Anki answered; `null` while offline/unavailable.
	 *  (64-bit narrowed at the IPC edge — specta forbids BigInt-style types.)
	 */
	due_total: number | null,
	/**
	 *  Human note when Anki did not answer ("Anki offline", or the failure
	 *  detail); `null` when `due_total` is present.
	 */
	note: string | null,
};

/**
 *  IPC shape of a card. The DB `BIGINT` id narrows to 32-bit at this edge
 *  (specta forbids BigInt-style types; ids are tiny in this app); the due
 *  date crosses as RFC 3339 — the UI only displays it.
 */
export type CardDto = {
	id: number,
	deck: string | null,
	front: string,
	back: string,
	/**  RFC 3339; `null` only for a card that never entered scheduling. */
	due: string | null,
	/**  `"learning" | "review" | "relearning"`; `null` = never reviewed (new). */
	state: string | null,
	reps: number,
};

/**  The daily queue: one IPC call answering "what do I study now". */
export type QueueDto = {
	anki: AnkiHeaderDto,
	/**
	 *  Track sections in stable rotation order (fundamentos → system-design
	 *  → videos); tracks with nothing to show are omitted.
	 */
	tracks: TrackQueueDto[],
};

/**
 *  One surfaced queue item. `stale` marks an `in_progress` chunk untouched
 *  for 14+ days — surfaced ahead of the track's new chunks (EARS). The DB
 *  `BIGINT` id narrows to 32-bit at this edge — ids are tiny in this app
 *  (same narrowing as `ReindexResponse`).
 */
export type QueueItemDto = {
	chunk_id: number,
	track: string,
	title: string,
	vault_path: string,
	/**  `"queued"` or `"in_progress"` (the queue-facing pair). */
	status: string,
	stale: boolean,
	est_minutes: number | null,
};

export type ReindexResponse = {
	sources: number,
	chunks: number,
	/**  Chunks seeded done by the `scope.md` rules in this pass. */
	done_seeded: number,
};

/**
 *  IPC shape of the study session. The DB `BIGINT` ids and the duration
 *  narrow to 32-bit at this edge (specta forbids BigInt-style types; values
 *  are tiny in this app).
 */
export type SessionDto = {
	session_id: number,
	/**  The chunk being studied (the open session's stage row names it). */
	chunk_id: number,
	/**  `false` while the session is open. */
	closed: boolean,
	/**  Logged seconds, present once the session is stopped. */
	duration_seconds: number | null,
};

/**
 *  IPC shape of the settings aggregate. `track_positions` only carries tracks
 *  with an explicit override; keys are track names, values are the chunk
 *  `vault_path` the track is at (domain::Settings semantics).
 */
export type SettingsDto = {
	vault_path: string | null,
	track_positions: { [key in string]: string },
};

export type TrackQueueDto = {
	track: string,
	/**
	 *  Surfacing order: stale first, then the fresh frontier, then the next
	 *  new chunk (specs/queue-slice/design.md).
	 */
	items: QueueItemDto[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

