// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  Re-index the vault: walk tracks + videos, seed from `scope.md`, upsert
	 *  idempotently on `vault_path`. Never duplicates rows; never regresses
	 *  chunk progress.
	 */
	reindex: (vaultPath: string | null) => typedError<ReindexResponse, string>(__TAURI_INVOKE("reindex", { vaultPath })),
	getSettings: () => typedError<SettingsDto, string>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Partial update: `vault_path: null` leaves it unchanged (the screen only
	 *  sends what the user edits); a blank position clears that track's override.
	 *  Returns the stored state so the UI syncs to what actually persisted.
	 */
	setSettings: (settings: SettingsDto) => typedError<SettingsDto, string>(__TAURI_INVOKE("set_settings", { settings })),
};

/* Types */
export type ReindexResponse = {
	sources: number,
	chunks: number,
	/**  Chunks seeded done by the `scope.md` rules in this pass. */
	done_seeded: number,
};

/**
 *  IPC shape of the settings aggregate. `track_positions` only carries tracks
 *  with an explicit override; keys are track names, values are the chunk
 *  `vault_path` the track is at (domain::Settings semantics).
 */
export type SettingsDto = {
	vault_path: string | null,
	track_positions: { [key in string]: string },
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

